export const FETCH_CONTACT_DETAIL_REQUEST = 'FETCH_CONTACT_DETAIL_REQUEST'
export const FETCH_CONTACT_DETAIL_SUCCESS = 'FETCH_CONTACT_DETAIL_SUCCESS'
export const FETCH_CONTACT_DETAIL_FAILURE = 'FETCH_CONTACT_DETAIL_FAILURE'