export const FETCH_CONTACT_UPDATE_REQUEST = 'FETCH_CONTACT_UPDATE_REQUEST'
export const FETCH_CONTACT_UPDATE_SUCCESS = 'FETCH_CONTACT_UPDATE_SUCCESS'
export const FETCH_CONTACT_UPDATE_FAILURE = 'FETCH_CONTACT_UPDATE_FAILURE'