export const FETCH_CONTACT_DELETE_REQUEST = 'FETCH_CONTACT_DELETE_REQUEST'
export const FETCH_CONTACT_DELETE_SUCCESS = 'FETCH_CONTACT_DELETE_SUCCESS'
export const FETCH_CONTACT_DELETE_FAILURE = 'FETCH_CONTACT_DELETE_FAILURE'