export const FETCH_CONTACT_ADD_REQUEST = 'FETCH_CONTACT_ADD_REQUEST'
export const FETCH_CONTACT_ADD_SUCCESS = 'FETCH_CONTACT_ADD_SUCCESS'
export const FETCH_CONTACT_ADD_FAILURE = 'FETCH_CONTACT_ADD_FAILURE'